version: "3"
services:
  #MySQL Database image
  my_database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Kolakadri1
      MYSQL_DATABASE: travelbetablog
      MYSQL_USER: travelbeta_blog
      MYSQL_PASSWORD:tr@v3lb3t@
    volumes:
      - mysql:/var/lib/mysql

  #WordPress image based on Apache
  wordpress:
    depends_on:
      - travelbetablog
    image: wordpress:6.1.1
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: 127.0.0.1:80
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: tr@v3lb3t@
      WORDPRESS_DB_NAME: my_wp_database
    volumes:
      ["./:/var/www/html"]
volumes:
  mysql: {}
